version: '3'
services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
  api:
    build: .
    ports:
      - '8080:80'
    volumes:
      - .:/usr/local/apache2/cgi-bin/weather
