version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
  api:
    build: .
    ports:
      - '8080:80'
    environment:
      - REDIS_SERVER=redis:6379
    volumes:
      - .:/usr/local/apache2/cgi-bin/weather
